### ISSUE TITLE
Questions to build your project

### ISSUE THREAD

**Issue by DarkShadowNight** [ArminJo/Ultimate-Battery-Tester#3]
Hello,

I like your project, Yet I am not able to replicate.
Some general remarks, questions:

- ADC_INTERNAL_REFERENCE_MILLIVOLT: Might need to explain how to measure to some less advanced users.
- ADC_CHANNEL_VOLTAGE: Watch out it's channel and not pin numbers, took me quite some time to figure out!
- ADC_CHANNEL_CURRENT / ADC_CHANNEL_LOGGER_CURRENT: What is the difference, I don't understand.
- Why is the internal LED flashing (pin 13), Timer running for PWM buzzer?
- ONLY_LOGGER_MODE_PIN: How it's measured when not connected to ground?
- LOGGER_SHUNT_RESISTOR_MILLIOHM : How, why, when?
- #define USE_PARALLEL_LCD //#define USE_SERIAL_LCD: Is this a nice way to switchover to I2C to comment and uncomment here?
#define ONLY_PLOTTER_OUTPUT_PIN and #define ADC_CHANNEL_LOGGER_CURRENT is a disaster it suddenly redeclarates if you think you have done your declarations already.
- #define LCD_COLUMNS 16 and #define LCD_ROWS 2: Not friendly on 20 * 4 display for erasing additional characters correctly.

Thanks

**Comment by ArminJo** [comment]
Hi, thanks for the feedback 👍 .
I tried to document most of your concerns, maybe you can check again and update your feedback.
Logger functionality is not yet properly tested...

**Comment by DarkShadowNight** [comment]
It is working now, thanks!
Why not include softwareserial for debugging / tracing?

https://github.com/salaiaungmyintmyat/OnePinOnly_SoftwareSerial

**Comment by ArminJo** [comment]
> Why not include softwareserial for debugging / tracing?

The standard serial is available for this, so why do you ask?

**Comment by DarkShadowNight** [comment]
Might be easy to have the debug output and trace output on a separate pin
Going to try to change your code to use this plotter, could be a nice alternative for the Arduino plotter:
https://hackaday.io/project/181686-better-serial-plotter/details
